# __📊SQL WORK ENVIOROMENT - HOSPITAL DATASET ANALYSIS 🏥__
---

## 🚨 __¿Cómo usar este archivo?__ 🤔

<p align="justify">
El presente archivo se constituye como una herramienta generadora de ambiente para el desarrollo de código SQL en Google Colab. Sus objetivo son: </p>

* <p align="justify"> Permitir al estudiante acceder a una base de datos que cuenta con más de 800,000 registros asociados a distintas variables relativas al rubro de prestación de servicios de salud (rubro hospitalario) :. </p>

* <p align="justify"> Generar un ambiente del trabajo donde los estudiantes puedan escribir, depurar y generar código SQL para realizar cosultas sobre la base de datos generada. </p>

* <p align="justify"> Aprender a usar SQL como herramienta de comunicación de insights y como pueden utilizarse para responder la pregunta de negocio o hipótesis que sea de interés para los stakeholders.
</p>

* <p align="justify">  Generar instancias que impliquen el manejo simultaneo de múltiples tablas en una base de datos.
</p>

<p align="justify">
El contexto viene dado por una 👉 <a href="https://github.com/hectorhormazabal-tt/TT-SQL-DA-95/blob/master/Data_set_hospital_generator.ipynb"> generación de data del rubro hospitalario/servicio de salud</a> 👈, que tiene por finalidad generar una instancia que permite al estudiante comprender la relación entre tablas, generación de consultas SQL de distinta complejidad, uso de CTE, filtros y sumarios.
</p>

---

##🖊️📖✏️📚 __INSTRUCCIONES DE USO__ 📋

 <p align="justify">

* __STEP 1️⃣:__ <p align="justify">  El chunk de código que viene a continuación tiene <b>dos funciones principales:</b>
</p>

<p align="justify">

**(1) Conectar** nuestro entorno con las bases de datos generadas para nuestro propósito de aprendizaje.
</p>

<p align="justify">

**(2) Generar un entorno de programación en SQL** idéntico a los motores frecuentemente usados en la industrial.
</p>

<p align="justify">
<b>Si es de su interés</b>, puedes hacer click en el botón ✨<b><font color="green">Mostrar código</font></b>✨, para poder ver con todo detalle el proceso mencionado en (1) y (2). Si no es así, simplemente omita esta opción. Sea cual sea el caso, <b><font color="red">debe dar click en el botón de run</font> </b> para poder generar la base de datos y activar el ambiente.
</p>

<p align = "justify">
Listo! La base de datos ha sido generada y ya podemos ver las tablas disponibles (rutas). También el ambiente para poder generar SQL-queries ha sido activado.
</p>

* __STEP 2️⃣:__ <p align="justify">

 Listo! Luego del paso anterior, ya puedes comenzar a generar consultas en este Google Colab y consultar la base de datos que ha sido generada (usando sus rutas). Para eso, simplemente debemos crear un nuevo chunck de código y escribir la <b><font color="cian">palabra mágica:</font></b> <b><font color="blue">%%sql</font></b>✨ en nuestro chunck de código y listo ✅, en ese chunck puedes ejecutar código SQL como lo harías en cualquier plataforma 🛢️.
</p>

In [20]:
#@title 🛢️📊 __STEP 1:__ Conectémonos a nuestra base de datos y activemos nuestro ambiente 🚀 { display-mode: "form" }

import pandas as pd
import sqlite3
import time
from IPython.core.magic import register_cell_magic
from IPython.display import display, HTML, clear_output
from tqdm.notebook import tqdm

# 1. Configuración de enlaces
datasets = {
    'tt_da_95_data_hospital_diagnoses': "https://raw.githubusercontent.com/hectorhormazabal-tt/TT-SQL-DA-95/refs/heads/master/diagnoses_dim.csv",
    'tt_da_95_data_hospital_appointments': "https://raw.githubusercontent.com/hectorhormazabal-tt/TT-SQL-DA-95/refs/heads/master/emergency_appointments.csv",
    'tt_da_95_data_hospital_patients': "https://raw.githubusercontent.com/hectorhormazabal-tt/TT-SQL-DA-95/refs/heads/master/patients_dim.csv"
}

# 2. Conexión a la base de datos en memoria
connector = sqlite3.connect(':memory:')

# 3. Proceso de carga con Barra de Progreso Verde
print("⬇️🗂️ Initiating data download and synchronization.....🔄⚙️")
summary_data = []

# Usamos tqdm para la barra visual
for name, url in tqdm(datasets.items(), desc="Cargando Tablas", bar_format='{l_bar}{bar:20}| {n_fmt}/{total_fmt}'):
    # Descarga
    df = pd.read_csv(url)

    # Conversión a SQL
    df.to_sql(name, connector, index=False, if_exists='replace')

    # Guardar info para el resumen
    summary_data.append({
        "Table route": f"{name}",
        "Row": f"{len(df):,}",
        "Columns": len(df.columns)
    })
    time.sleep(0.5) # Breve delay para que la barra sea visible

# 4. Palabra mágica %%sql
@register_cell_magic
def sql(line, cell):
    try:
        resultado = pd.read_sql(cell, connector)
        clear_output(wait=True)
        display(HTML("<b style='color: #4CAF50;'>✅ Query completed successfully:</b>"))
        return display(resultado)
    except Exception as e:
        clear_output(wait=True)
        display(HTML(f"<b style='color: #F44336;'>❌ Query execution failed:</b><br><code style='color: grey;'>{str(e)}</code>"))

# 5. Interfaz final para el alumno
clear_output()
display(HTML("<h2 style='color: #0636F9'>✨ Database initialized - Hospital data ✨</h2>"))
display(HTML("<p>Data has been successfully loaded. Please use these names for your queries:</p>"))

# Mostramos el resumen en una tabla estética
display(pd.DataFrame(summary_data))

print("\n ✨🏥 ALL DONE! YOU ARE READY TO PRACTICE YOUR QUERY SKILLS! 💊🌡️🩹💉🩺✨")

                           Table route      Row  Columns
0     tt_da_95_data_hospital_diagnoses       15        6
1  tt_da_95_data_hospital_appointments  800,000       11
2      tt_da_95_data_hospital_patients   25,000       10

 ✨🏥 ALL DONE! YOU ARE READY TO PRACTICE YOUR QUERY SKILLS! 💊🌡️🩹💉🩺✨

### 📌__Sumario de las tablas__📋


<p align="justify">

<p align="justify"> <b>Table name:</b> <code style="color: #ffffff; background-color: #F0E325; padding: 2px 6px; border-radius: 4px;">tt_da_95_data_hospital_appointments</code> </p>

| Column name | Data type | Example | Description|
| :--- | :--- | :--- | :--- |
| **appointment_id** | `INT` | `10` | Identificador único de la atención en urgencias. |
| **patient_id** | `TEXT` | `PAT-25-12835` | ID único del paciente (usar para `JOIN` con tabla de pacientes). |
| **icd10_id** | `TEXT` | `ICD-110` | Código internacional de enfermedad (usar para `JOIN` con diagnósticos). |
| **admission_date** | `TEXT` | `2025-07-21 23:54` | Fecha y hora exacta del ingreso del paciente. |
| **triage_level** | `TEXT` | `Red` | Gravedad del paciente: Rojo (Crítico), Amarillo (Urgente), Azul (No urgente). |
| **systolic_bp** | `INT` | `134` | Presión arterial sistólica (valor máximo). |
| **diastolic_bp** | `INT` | `104` | Presión arterial diastólica (valor mínimo). |
| **heart_rate** | `INT` | `82` | Frecuencia cardíaca medida en latidos por minuto (BPM). |
| **temp_celsius** | `FLOAT` | `36.9` | Temperatura corporal del paciente al ingresar. |
| **total_cost** | `FLOAT` | `3604.36` | Costo monetario total de la atención recibida. |
| **hospital_branch** | `TEXT` | `Polanco` | Nombre de la sucursal u hospital donde se realizó la atención. |

<br>
<p align="justify"> <b>Table name:</b> <code style="color: #ffffff; background-color: #F0E325; padding: 2px 6px; border-radius: 4px;">tt_da_95_data_hospital_diagnoses</code> </p>

| Column name | Data type | Example | Description|
| :--- | :--- | :--- | :--- |
| **icd10_id** | `TEXT` | `ICD-101` | Código identificador de la enfermedad (usar para `JOIN`). |
| **diagnosis_name** | `TEXT` | `Acute Myocardial Infarction` | Nombre clínico de la patología. |
| **medical_specialty** | `TEXT` | `Cardiology` | Especialidad médica encargada del caso. |
| **risk_score** | `INT` | `9` | Escala de riesgo (1-10) del diagnóstico. |
| **is_contagious** | `BOOLEAN` | `0` | Indica si es contagioso (1 = Sí, 0 = No). |
| **avg_recovery_weeks**| `INT` | `12` | Tiempo promedio estimado de recuperación en semanas. |

<br>
<p align="justify"> <b>Table name:</b> <code style="color: #ffffff; background-color: #F0E325; padding: 2px 6px; border-radius: 4px;">tt_da_95_data_hospital_patients 	</code> </p>

| Column name | Data type | Example | Description |
| :--- | :--- | :--- | :--- |
| **patient_id** | `TEXT` | `PAT-25-00001` | Identificador único del paciente (usar para `JOIN`). |
| **full_name** | `TEXT` | `Patient_1` | Nombre completo del paciente. |
| **gender** | `TEXT` | `F` | Género: F (Femenino), M (Masculino), NB (No binario). |
| **birth_date** | `TEXT` | `2009-10-06` | Fecha de nacimiento (útil para calcular la edad). |
| **occupation** | `TEXT` | `Student` | Ocupación o situación laboral actual. |
| **state_mx** | `TEXT` | `CDMX` | Estado de la República Mexicana donde reside. |
| **blood_type** | `TEXT` | `B+` | Grupo sanguíneo y factor Rh. |
| **height_m** | `FLOAT` | `1.63` | Altura del paciente medida en metros. |
| **weight_kg** | `FLOAT` | `91.7` | Peso del paciente medido en kilogramos. |
| **insurance_provider**| `TEXT` | `ISSSTE` | Institución o aseguradora del paciente (IMSS, GNP, etc.). |

###  👩🏻‍💻🕵🏻‍♂️ __STEP 2: Comencemos a hacer consultas!__ 🗂️📡👩🏻‍💻

### 📢__Ambiente de práctica__ 💪🏼

<p align = "justify">
A continuación, nos pondremos en los zapatos de nuestros stakeholders y nos haremos preguntas que podrían llegar a ser de su interés, con el objetivo de orientar su proceso de toma de decisiones mediante el uso de SQL como herramienta dentro de nuestro arsenal como analistas de datos. </p>

## 📑__ANTES DE COMENZAR❗. BASIC SQL SENTENCES__ 🔍
| SQL Statement | Description | Classification |
| :--- | :--- | :--- |
| `SELECT` | Selecciona columnas específicas para extraer datos de una tabla. | Selección |
| `SELECT *` | Selecciona todos los campos disponibles en una tabla. | Selección |
| `DISTINCT` | Extrae valores únicos, eliminando los duplicados de una columna. | Selección |
| `WHERE` | Filtra las filas que cumplen con una condición determinada. | Filtrado |
| `AND` / `OR` | Combina múltiples criterios de búsqueda en una misma consulta. | Filtrado |
| `IN` | Comprueba si un valor coincide con cualquier elemento de una lista. | Filtrado |
| `LIKE` | Busca un patrón específico dentro de una cadena de texto (comodín `%`). | Filtrado |
| `BETWEEN` | Filtra valores dentro de un rango numérico o de fechas definido. | Filtrado |
| `ORDER BY` | Clasifica los resultados de forma ascendente (`ASC`) o descendente (`DESC`). | Ordenamiento |
| `GROUP BY` | Agrupa registros que tienen valores idénticos para realizar cálculos. | Agregación |
| `COUNT()` | Cuenta el número total de filas o registros en un grupo. | Agregación |
| `SUM()` | Suma todos los valores de una columna numérica. | Agregación |
| `AVG()` | Calcula el valor promedio de una columna numérica. | Agregación |
| `MIN()` / `MAX()` | Devuelve el valor mínimo o máximo de una columna respectivamente. | Agregación |
| `HAVING` | Aplica condiciones de filtrado a los resultados de una agregación. | Filtrado de Agregados |
| `CAST()` | Convierte una expresión de un tipo de dato a otro (ej. texto a número). | Conversión / Limpieza |
| `JOIN` | Combina filas de dos o más tablas basándose en una columna común. | Relación |
| `LIMIT` | Restringe la cantidad total de filas que devuelve la consulta. | Restricción |

### 📝 __SQL Query Template & Logic__

| Clause | Technical Syntax | Logic Flow |
| :--- | :--- | :--- |
| **SELECT** | `SELECT col_1, SUM(col_2) AS alias` | 5. Visualización |
| **FROM** | `FROM table_name` | 1. Origen de datos |
| **WHERE** | `WHERE col_1 > value` | 2. Filtro de filas |
| **GROUP BY** | `GROUP BY col_1` | 3. Agrupación |
| **HAVING** | `HAVING SUM(col_2) > value` | 4. Filtro de agregados |
| **ORDER BY** | `ORDER BY alias DESC` | 6. Ordenamiento |
| **LIMIT** | `LIMIT 10` | 7. Restricción |

###__🧩Basic query example__

In [21]:
%%sql
SELECT
*
FROM tt_da_95_data_hospital_appointments LIMIT 10

,appointment_id,patient_id,icd10_id,admission_date,triage_level,systolic_bp,diastolic_bp,heart_rate,temp_celsius,total_cost,hospital_branch
0,1,PAT-25-12835,ICD-110,2025-07-21 23:54:00,Yellow,134,104,82,36.9,3604.36,Centro
1,2,PAT-25-23799,ICD-115,2025-09-24 09:19:00,Blue,161,90,53,37.8,1672.30,Polanco
2,3,PAT-25-17072,ICD-101,2025-03-25 12:15:00,Red,160,101,102,36.6,81709.34,Polanco
3,4,PAT-25-02907,ICD-101,2025-08-21 21:54:00,Red,103,79,59,37.6,92072.24,Centro
4,5,PAT-25-22416,ICD-113,2025-12-29 13:26:00,Yellow,146,81,110,37.2,4178.57,Santa Fe
5,6,PAT-25-06217,ICD-102,2025-10-22 10:38:00,Orange,123,73,69,38.6,13783.14,Santa Fe
6,7,PAT-25-10256,ICD-102,2025-11-19 07:31:00,Orange,91,65,86,35.1,17013.61,Polanco
7,8,PAT-25-01891,ICD-102,2025-09-11 01:31:00,Orange,169,90,115,37.1,17962.29,Centro
8,9,PAT-25-21948,ICD-101,2025-01-23 13:51:00,Red,115,76,82,38.2,97996.36,Monterrey
9,10,PAT-25-03694,ICD-113,2025-01-04 22:51:00,Yellow,144,105,113,36.1,3830.98,Santa Fe